# -*- coding: utf-8 -*-
"""Prodigy-Task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reiPdpzZWEpCT-eZPScDLBOoUqwOsQb8

#Importing Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

"""#Reading and Analysing the file"""

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

df.isnull().sum()

df.dtypes

df.head()

"""#Handling Missing Values in the Data Set"""

df['Age'].fillna(df['Age'].median(), inplace=True)

df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

df.drop('Cabin', axis=1, inplace=True)

df

df.isnull().sum()

df['Survived'] = df['Survived'].astype('category')
df['Pclass'] = df['Pclass'].astype('category')

df

"""#Exploratary Data Analysis"""

df.describe()

from matplotlib import pyplot as plt
_df_12['PassengerId'].plot(kind='hist', bins=20, title='PassengerId')
plt.gca().spines[['top', 'right',]].set_visible(False)

df['Survived'].value_counts()

survived_male = df[(df['Survived'] == 1) & (df['Sex'] == 'male')]
survived_female = df[(df['Survived'] == 1) & (df['Sex'] == 'female')]

survived_male

survived_female

len(survived_male)

len(survived_female)

"""#Visulasing Insights

"""

import seaborn as sns
import matplotlib.pyplot as plt

# Survival distribution
sns.countplot(x='Survived', data=df)
plt.title("Survival Distribution")
plt.show()

# Survival by gender
sns.countplot(x='Survived', hue='Sex', data=df)
plt.title("Survival by Gender")
plt.show()

# Survival by passenger class
sns.countplot(x='Pclass', hue='Survived', data=df)
plt.title("Survival by Passenger Class")
plt.show()

# Distribution of age
plt.hist(df['Age'], bins=30, color='blue', edgecolor='black')
plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()